name = "gershon-task"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_SITE_URL = "https://task.gershoncrm.com"

# Run on the 1st of every month at 06:00 UTC
[triggers]
crons = ["0 6 1 * *"]
